# Generated by Django 5.0.7 on 2024-07-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_moviereview_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='genre',
            field=models.CharField(choices=[('ACTION', 'Action'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('SCI_FI', 'Science Fiction'), ('ROMANCE', 'Romance'), ('THRILLER', 'Thriller'), ('ANIMATION', 'Animation'), ('DOCUMENTARY', 'Documentary'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
